"""MCP type definitions — entities, responses, workflows, curation.

Re-exports all types for backward-compatible ``from app.mcp.types import X``.
"""

from app.mcp.types.curation import (
    ClassifyResult,
    CurateCandidate,
    CurateSetResult,
    DistributeResult,
    GapDescription,
    LibraryGapResult,
    MoodDistribution,
    SetReviewResult,
    WeakTransition,
)
from app.mcp.types.entities import (
    ArtistSummary,
    PlaylistDetail,
    PlaylistSummary,
    SetDetail,
    SetSummary,
    TrackDetail,
    TrackSummary,
)
from app.mcp.types.responses import (
    ActionResponse,
    EntityDetailResponse,
    EntityListResponse,
    FindResult,
    LibraryStats,
    MatchStats,
    PaginationInfo,
    SearchResponse,
)
from app.mcp.types.workflows import (
    AdjustmentPlan,
    DeliveryResult,
    ExportResult,
    ReorderSuggestion,
    SearchStrategy,
    SetBuildResult,
    SetCheatSheet,
    SetTrackItem,
    SetVersionSummary,
    SimilarTracksResult,
    SwapSuggestion,
    TransitionScoreResult,
    TransitionSummary,
)

__all__ = [
    "ActionResponse",
    "AdjustmentPlan",
    "ArtistSummary",
    "ClassifyResult",
    "CurateCandidate",
    "CurateSetResult",
    "DeliveryResult",
    "DistributeResult",
    "EntityDetailResponse",
    "EntityListResponse",
    "ExportResult",
    "FindResult",
    "GapDescription",
    "LibraryGapResult",
    "LibraryStats",
    "MatchStats",
    "MoodDistribution",
    "PaginationInfo",
    "PlaylistDetail",
    "PlaylistSummary",
    "ReorderSuggestion",
    "SearchResponse",
    "SearchStrategy",
    "SetBuildResult",
    "SetCheatSheet",
    "SetDetail",
    "SetReviewResult",
    "SetSummary",
    "SetTrackItem",
    "SetVersionSummary",
    "SimilarTracksResult",
    "SwapSuggestion",
    "TrackDetail",
    "TrackSummary",
    "TransitionScoreResult",
    "TransitionSummary",
    "WeakTransition",
]
