"""schema_v6_models

Revision ID: 8d5de96145e2
Revises: 
Create Date: 2026-02-12 20:46:45.535536
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.common


# revision identifiers, used by Alembic.
revision: str = '8d5de96145e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_sort', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_index('idx_artists_name_trgm', 'artists', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('dj_playlists',
    sa.Column('playlist_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('parent_playlist_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_app', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_playlist_id'], ['dj_playlists.playlist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_table('dj_sets',
    sa.Column('set_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_duration_ms', sa.Integer(), nullable=True),
    sa.Column('target_bpm_min', sa.Float(), nullable=True),
    sa.Column('target_bpm_max', sa.Float(), nullable=True),
    sa.Column('target_energy_arc', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('embedding_types',
    sa.Column('embedding_type', sa.Text(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('embedding_type')
    )
    op.create_table('feature_extraction_runs',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('pipeline_name', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('code_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_genre_id'], ['genres.genre_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keys',
    sa.Column('key_code', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_class', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('camelot', sa.Text(), nullable=True),
    sa.CheckConstraint('key_code = pitch_class * 2 + mode', name='keys_code_deterministic'),
    sa.PrimaryKeyConstraint('key_code')
    )
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_sort', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.SmallInteger(), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('provider_code')
    )
    op.create_table('spotify_album_metadata',
    sa.Column('spotify_album_id', sa.Text(), nullable=False),
    sa.Column('album_type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Text(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_album_id')
    )
    op.create_table('spotify_artist_metadata',
    sa.Column('spotify_artist_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_artist_id')
    )
    op.create_table('spotify_playlist_metadata',
    sa.Column('spotify_playlist_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('snapshot_id', sa.Text(), nullable=True),
    sa.Column('owner', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_playlist_id')
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('fingerprint_sha1', sa.LargeBinary(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_sort', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('fingerprint_sha1', name='tracks_fingerprint_uq')
    )
    op.create_index('idx_tracks_active', 'tracks', ['track_id'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('idx_tracks_title_trgm', 'tracks', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('transition_runs',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('pipeline_name', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.Text(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('audio_assets',
    sa.Column('asset_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.SmallInteger(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('source_run_id', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_run_id'], ['feature_extraction_runs.run_id'], name='fk_audio_assets_source_run', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('track_id', 'asset_type', 'source_run_id', name='audio_assets_uq')
    )
    op.create_index('idx_audio_assets_track', 'audio_assets', ['track_id', 'asset_type'], unique=False)
    op.create_table('beatport_metadata',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('beatport_track_id', sa.Text(), nullable=False),
    sa.Column('beatport_release_id', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key_code', sa.SmallInteger(), nullable=True),
    sa.Column('length_ms', sa.Integer(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('genre_name', sa.Text(), nullable=True),
    sa.Column('subgenre_name', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['key_code'], ['keys.key_code'], name='fk_beatport_key', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('beatport_track_id')
    )
    op.create_table('dj_app_exports',
    sa.Column('export_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('target_app', sa.SmallInteger(), nullable=False),
    sa.Column('export_format', sa.Text(), nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['dj_playlists.playlist_id'], ),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('dj_beatgrid',
    sa.Column('beatgrid_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('source_app', sa.SmallInteger(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('first_downbeat_ms', sa.Integer(), nullable=False),
    sa.Column('grid_offset_ms', sa.Integer(), nullable=True),
    sa.Column('grid_confidence', sa.Float(), nullable=True),
    sa.Column('is_variable_tempo', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beatgrid_id'),
    sa.UniqueConstraint('track_id', 'source_app', name='beatgrid_track_source_uq')
    )
    op.create_index('idx_beatgrid_canonical', 'dj_beatgrid', ['track_id'], unique=True, postgresql_where=sa.text('is_canonical = true'))
    op.create_table('dj_cue_points',
    sa.Column('cue_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('cue_kind', sa.SmallInteger(), nullable=False),
    sa.Column('hotcue_index', sa.SmallInteger(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('color_rgb', sa.Integer(), nullable=True),
    sa.Column('is_quantized', sa.Boolean(), nullable=True),
    sa.Column('source_app', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cue_id')
    )
    op.create_index('idx_cues_track', 'dj_cue_points', ['track_id', 'hotcue_index'], unique=False)
    op.create_table('dj_library_items',
    sa.Column('library_item_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.LargeBinary(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('source_app', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('library_item_id')
    )
    op.create_index('idx_dj_lib_track', 'dj_library_items', ['track_id'], unique=False)
    op.create_table('dj_playlist_items',
    sa.Column('playlist_item_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['dj_playlists.playlist_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_item_id'),
    sa.UniqueConstraint('playlist_id', 'sort_index', name='dj_playlist_items_uq')
    )
    op.create_table('dj_saved_loops',
    sa.Column('loop_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('in_ms', sa.Integer(), nullable=False),
    sa.Column('out_ms', sa.Integer(), nullable=False),
    sa.Column('length_ms', sa.Integer(), nullable=False),
    sa.Column('hotcue_index', sa.SmallInteger(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('is_active_on_load', sa.Boolean(), nullable=True),
    sa.Column('color_rgb', sa.Integer(), nullable=True),
    sa.Column('source_app', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('out_ms > in_ms AND length_ms = out_ms - in_ms', name='loop_range_check'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loop_id')
    )
    op.create_index('idx_loops_track', 'dj_saved_loops', ['track_id', 'hotcue_index'], unique=False)
    op.create_table('dj_set_versions',
    sa.Column('set_version_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=True),
    sa.Column('generator_run', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['dj_sets.set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_version_id')
    )
    op.create_index('idx_set_versions_set', 'dj_set_versions', ['set_id'], unique=False)
    op.create_table('key_edges',
    sa.Column('from_key_code', sa.SmallInteger(), nullable=False),
    sa.Column('to_key_code', sa.SmallInteger(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_key_code'], ['keys.key_code'], ),
    sa.ForeignKeyConstraint(['to_key_code'], ['keys.key_code'], ),
    sa.PrimaryKeyConstraint('from_key_code', 'to_key_code')
    )
    op.create_table('provider_track_ids',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.SmallInteger(), nullable=False),
    sa.Column('provider_track_id', sa.Text(), nullable=False),
    sa.Column('provider_country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.UniqueConstraint('provider_id', 'provider_track_id', 'provider_country', name='provider_track_ids_uq', postgresql_nulls_not_distinct=True)
    )
    op.create_index('idx_provider_track_ids_track', 'provider_track_ids', ['track_id'], unique=False)
    op.create_table('raw_provider_responses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.SmallInteger(), nullable=False),
    sa.Column('provider_track_id', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'ingested_at'),
    postgresql_partition_by='RANGE (ingested_at)'
    )
    op.create_index('idx_raw_provider_track', 'raw_provider_responses', ['track_id', 'provider_id'], unique=False)
    op.create_table('releases',
    sa.Column('release_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_precision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.label_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_table('soundcloud_metadata',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('soundcloud_track_id', sa.Text(), nullable=False),
    sa.Column('soundcloud_user_id', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('playback_count', sa.Integer(), nullable=True),
    sa.Column('favoritings_count', sa.Integer(), nullable=True),
    sa.Column('reposts_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('downloadable', sa.Boolean(), nullable=True),
    sa.Column('streamable', sa.Boolean(), nullable=True),
    sa.Column('permalink_url', sa.Text(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('soundcloud_track_id')
    )
    op.create_table('spotify_audio_features',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('loudness', sa.Float(), nullable=False),
    sa.Column('speechiness', sa.Float(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=False),
    sa.Column('instrumentalness', sa.Float(), nullable=False),
    sa.Column('liveness', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('time_signature', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('spotify_metadata',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.Text(), nullable=False),
    sa.Column('spotify_album_id', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_precision', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['spotify_album_id'], ['spotify_album_metadata.spotify_album_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('spotify_track_id')
    )
    op.create_table('track_artists',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id', 'role')
    )
    op.create_index('idx_track_artists_artist', 'track_artists', ['artist_id'], unique=False)
    op.create_table('track_audio_features_computed',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('tempo_confidence', sa.Float(), nullable=False),
    sa.Column('bpm_stability', sa.Float(), nullable=False),
    sa.Column('is_variable_tempo', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('lufs_i', sa.Float(), nullable=False),
    sa.Column('lufs_s_mean', sa.Float(), nullable=True),
    sa.Column('lufs_m_max', sa.Float(), nullable=True),
    sa.Column('rms_dbfs', sa.Float(), nullable=False),
    sa.Column('true_peak_db', sa.Float(), nullable=True),
    sa.Column('crest_factor_db', sa.Float(), nullable=True),
    sa.Column('lra_lu', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=False),
    sa.Column('energy_max', sa.Float(), nullable=False),
    sa.Column('energy_std', sa.Float(), nullable=False),
    sa.Column('energy_slope_mean', sa.Float(), nullable=True),
    sa.Column('sub_energy', sa.Float(), nullable=True),
    sa.Column('low_energy', sa.Float(), nullable=True),
    sa.Column('lowmid_energy', sa.Float(), nullable=True),
    sa.Column('mid_energy', sa.Float(), nullable=True),
    sa.Column('highmid_energy', sa.Float(), nullable=True),
    sa.Column('high_energy', sa.Float(), nullable=True),
    sa.Column('low_high_ratio', sa.Float(), nullable=True),
    sa.Column('sub_lowmid_ratio', sa.Float(), nullable=True),
    sa.Column('centroid_mean_hz', sa.Float(), nullable=True),
    sa.Column('rolloff_85_hz', sa.Float(), nullable=True),
    sa.Column('rolloff_95_hz', sa.Float(), nullable=True),
    sa.Column('flatness_mean', sa.Float(), nullable=True),
    sa.Column('flux_mean', sa.Float(), nullable=True),
    sa.Column('flux_std', sa.Float(), nullable=True),
    sa.Column('slope_db_per_oct', sa.Float(), nullable=True),
    sa.Column('contrast_mean_db', sa.Float(), nullable=True),
    sa.Column('key_code', sa.SmallInteger(), nullable=False),
    sa.Column('key_confidence', sa.Float(), nullable=False),
    sa.Column('is_atonal', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('chroma', app.models.common.VectorType(dim=12), nullable=False),
    sa.Column('hnr_mean_db', sa.Float(), nullable=True),
    sa.Column('hp_ratio', sa.Float(), nullable=True),
    sa.Column('onset_rate_mean', sa.Float(), nullable=True),
    sa.Column('onset_rate_max', sa.Float(), nullable=True),
    sa.Column('pulse_clarity', sa.Float(), nullable=True),
    sa.Column('kick_prominence', sa.Float(), nullable=True),
    sa.Column('computed_from_asset_type', sa.SmallInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['key_code'], ['keys.key_code'], ),
    sa.ForeignKeyConstraint(['run_id'], ['feature_extraction_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'run_id')
    )
    op.create_index('idx_taf_bpm', 'track_audio_features_computed', ['bpm'], unique=False)
    op.create_index('idx_taf_chroma', 'track_audio_features_computed', ['chroma'], unique=False, postgresql_using='hnsw', postgresql_ops={'chroma': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 200})
    op.create_table('track_embeddings',
    sa.Column('embedding_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('embedding_type', sa.Text(), nullable=False),
    sa.Column('vector', app.models.common.VectorType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_type'], ['embedding_types.embedding_type'], ),
    sa.ForeignKeyConstraint(['run_id'], ['feature_extraction_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('track_id', 'embedding_type', 'run_id', name='embeddings_uq')
    )
    op.create_index('idx_embeddings_type', 'track_embeddings', ['embedding_type', 'track_id'], unique=False)
    op.create_table('track_genres',
    sa.Column('track_genre_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('source_provider_id', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_provider_id'], ['providers.provider_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_genre_id'),
    sa.UniqueConstraint('track_id', 'genre_id', 'source_provider_id', name='track_genres_uq', postgresql_nulls_not_distinct=True)
    )
    op.create_table('track_sections',
    sa.Column('section_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('range_ms', app.models.common.Int4RangeType(), nullable=False),
    sa.Column('section_type', sa.SmallInteger(), nullable=False),
    sa.Column('section_duration_ms', sa.Integer(), nullable=False),
    sa.Column('section_energy_mean', sa.Float(), nullable=True),
    sa.Column('section_energy_max', sa.Float(), nullable=True),
    sa.Column('section_energy_slope', sa.Float(), nullable=True),
    sa.Column('section_centroid_hz', sa.Float(), nullable=True),
    sa.Column('section_flux', sa.Float(), nullable=True),
    sa.Column('section_onset_rate', sa.Float(), nullable=True),
    sa.Column('section_pulse_clarity', sa.Float(), nullable=True),
    sa.Column('boundary_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('NOT upper_inf(range_ms) AND NOT lower_inf(range_ms)', name='sections_range_bounded'),
    sa.CheckConstraint('section_duration_ms = upper(range_ms) - lower(range_ms)', name='sections_duration_matches_range'),
    sa.ForeignKeyConstraint(['run_id'], ['feature_extraction_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('section_id', 'track_id', name='sections_track_uq')
    )
    op.create_index('idx_sections_track_range', 'track_sections', ['track_id', 'range_ms'], unique=False, postgresql_using='gist')
    op.create_index('idx_sections_track_run', 'track_sections', ['track_id', 'run_id'], unique=False)
    op.create_table('track_timeseries_refs',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_set', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('hop_length', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.Text(), server_default=sa.text("'float32'"), nullable=False),
    sa.Column('shape', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['feature_extraction_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'run_id', 'feature_set')
    )
    op.create_table('transition_candidates',
    sa.Column('from_track_id', sa.Integer(), nullable=False),
    sa.Column('to_track_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('bpm_distance', sa.Float(), nullable=False),
    sa.Column('key_distance', sa.Float(), nullable=False),
    sa.Column('embedding_similarity', sa.Float(), nullable=True),
    sa.Column('energy_delta', sa.Float(), nullable=True),
    sa.Column('is_fully_scored', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('from_track_id <> to_track_id', name='candidates_direction'),
    sa.ForeignKeyConstraint(['from_track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['transition_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_track_id', 'to_track_id', 'run_id')
    )
    op.create_index('idx_candidates_from', 'transition_candidates', ['from_track_id', 'bpm_distance', 'key_distance'], unique=False, postgresql_where=sa.text('is_fully_scored = false'))
    op.create_index('idx_candidates_to', 'transition_candidates', ['to_track_id'], unique=False, postgresql_where=sa.text('is_fully_scored = false'))
    op.create_table('dj_beatgrid_change_points',
    sa.Column('point_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('beatgrid_id', sa.BigInteger(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['beatgrid_id'], ['dj_beatgrid.beatgrid_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index('idx_beatgrid_cp_grid', 'dj_beatgrid_change_points', ['beatgrid_id', 'position_ms'], unique=False)
    op.create_table('dj_set_constraints',
    sa.Column('constraint_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('set_version_id', sa.BigInteger(), nullable=False),
    sa.Column('constraint_type', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_version_id'], ['dj_set_versions.set_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_index('idx_set_constraints_version', 'dj_set_constraints', ['set_version_id'], unique=False)
    op.create_table('track_releases',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.SmallInteger(), nullable=True),
    sa.Column('disc_number', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.release_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'release_id')
    )
    op.create_index('idx_track_releases_release', 'track_releases', ['release_id'], unique=False)
    op.create_table('transitions',
    sa.Column('transition_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('from_track_id', sa.Integer(), nullable=False),
    sa.Column('to_track_id', sa.Integer(), nullable=False),
    sa.Column('from_section_id', sa.BigInteger(), nullable=True),
    sa.Column('to_section_id', sa.BigInteger(), nullable=True),
    sa.Column('overlap_ms', sa.Integer(), nullable=False),
    sa.Column('bpm_distance', sa.Float(), nullable=False),
    sa.Column('energy_step', sa.Float(), nullable=False),
    sa.Column('centroid_gap_hz', sa.Float(), nullable=True),
    sa.Column('low_conflict_score', sa.Float(), nullable=True),
    sa.Column('overlap_score', sa.Float(), nullable=True),
    sa.Column('groove_similarity', sa.Float(), nullable=True),
    sa.Column('key_distance_weighted', sa.Float(), nullable=True),
    sa.Column('transition_quality', sa.Float(), nullable=False),
    sa.Column('trans_feature', app.models.common.VectorType(dim=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('from_track_id <> to_track_id', name='transitions_direction'),
    sa.ForeignKeyConstraint(['from_section_id', 'from_track_id'], ['track_sections.section_id', 'track_sections.track_id'], name='fk_from_section', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['transition_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_section_id', 'to_track_id'], ['track_sections.section_id', 'track_sections.track_id'], name='fk_to_section', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transition_id'),
    sa.UniqueConstraint('from_track_id', 'to_track_id', 'from_section_id', 'to_section_id', 'run_id', name='transitions_uq', postgresql_nulls_not_distinct=True)
    )
    op.create_index('idx_transitions_feature', 'transitions', ['trans_feature'], unique=False, postgresql_using='hnsw', postgresql_ops={'trans_feature': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 200})
    op.create_table('dj_set_items',
    sa.Column('set_item_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('set_version_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('transition_id', sa.BigInteger(), nullable=True),
    sa.Column('in_section_id', sa.BigInteger(), nullable=True),
    sa.Column('out_section_id', sa.BigInteger(), nullable=True),
    sa.Column('mix_in_ms', sa.Integer(), nullable=True),
    sa.Column('mix_out_ms', sa.Integer(), nullable=True),
    sa.Column('planned_eq', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['in_section_id', 'track_id'], ['track_sections.section_id', 'track_sections.track_id'], name='fk_set_item_in_section', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['out_section_id', 'track_id'], ['track_sections.section_id', 'track_sections.track_id'], name='fk_set_item_out_section', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_version_id'], ['dj_set_versions.set_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transition_id'], ['transitions.transition_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('set_item_id'),
    sa.UniqueConstraint('set_version_id', 'sort_index', name='set_items_sort_uq')
    )
    op.create_index('idx_set_items_track', 'dj_set_items', ['track_id'], unique=False)
    op.create_index('idx_set_items_version', 'dj_set_items', ['set_version_id'], unique=False)
    op.create_table('dj_set_feedback',
    sa.Column('feedback_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('set_version_id', sa.BigInteger(), nullable=False),
    sa.Column('set_item_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('feedback_type', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_item_id'], ['dj_set_items.set_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_version_id'], ['dj_set_versions.set_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('idx_feedback_set', 'dj_set_feedback', ['set_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_set', table_name='dj_set_feedback')
    op.drop_table('dj_set_feedback')
    op.drop_index('idx_set_items_version', table_name='dj_set_items')
    op.drop_index('idx_set_items_track', table_name='dj_set_items')
    op.drop_table('dj_set_items')
    op.drop_index('idx_transitions_feature', table_name='transitions', postgresql_using='hnsw', postgresql_ops={'trans_feature': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 200})
    op.drop_table('transitions')
    op.drop_index('idx_track_releases_release', table_name='track_releases')
    op.drop_table('track_releases')
    op.drop_index('idx_set_constraints_version', table_name='dj_set_constraints')
    op.drop_table('dj_set_constraints')
    op.drop_index('idx_beatgrid_cp_grid', table_name='dj_beatgrid_change_points')
    op.drop_table('dj_beatgrid_change_points')
    op.drop_index('idx_candidates_to', table_name='transition_candidates', postgresql_where=sa.text('is_fully_scored = false'))
    op.drop_index('idx_candidates_from', table_name='transition_candidates', postgresql_where=sa.text('is_fully_scored = false'))
    op.drop_table('transition_candidates')
    op.drop_table('track_timeseries_refs')
    op.drop_index('idx_sections_track_run', table_name='track_sections')
    op.drop_index('idx_sections_track_range', table_name='track_sections', postgresql_using='gist')
    op.drop_table('track_sections')
    op.drop_table('track_genres')
    op.drop_index('idx_embeddings_type', table_name='track_embeddings')
    op.drop_table('track_embeddings')
    op.drop_index('idx_taf_chroma', table_name='track_audio_features_computed', postgresql_using='hnsw', postgresql_ops={'chroma': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 200})
    op.drop_index('idx_taf_bpm', table_name='track_audio_features_computed')
    op.drop_table('track_audio_features_computed')
    op.drop_index('idx_track_artists_artist', table_name='track_artists')
    op.drop_table('track_artists')
    op.drop_table('spotify_metadata')
    op.drop_table('spotify_audio_features')
    op.drop_table('soundcloud_metadata')
    op.drop_table('releases')
    op.drop_index('idx_raw_provider_track', table_name='raw_provider_responses')
    op.drop_table('raw_provider_responses')
    op.drop_index('idx_provider_track_ids_track', table_name='provider_track_ids')
    op.drop_table('provider_track_ids')
    op.drop_table('key_edges')
    op.drop_index('idx_set_versions_set', table_name='dj_set_versions')
    op.drop_table('dj_set_versions')
    op.drop_index('idx_loops_track', table_name='dj_saved_loops')
    op.drop_table('dj_saved_loops')
    op.drop_table('dj_playlist_items')
    op.drop_index('idx_dj_lib_track', table_name='dj_library_items')
    op.drop_table('dj_library_items')
    op.drop_index('idx_cues_track', table_name='dj_cue_points')
    op.drop_table('dj_cue_points')
    op.drop_index('idx_beatgrid_canonical', table_name='dj_beatgrid', postgresql_where=sa.text('is_canonical = true'))
    op.drop_table('dj_beatgrid')
    op.drop_table('dj_app_exports')
    op.drop_table('beatport_metadata')
    op.drop_index('idx_audio_assets_track', table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_table('transition_runs')
    op.drop_index('idx_tracks_title_trgm', table_name='tracks', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_tracks_active', table_name='tracks', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('tracks')
    op.drop_table('spotify_playlist_metadata')
    op.drop_table('spotify_artist_metadata')
    op.drop_table('spotify_album_metadata')
    op.drop_table('providers')
    op.drop_table('labels')
    op.drop_table('keys')
    op.drop_table('genres')
    op.drop_table('feature_extraction_runs')
    op.drop_table('embedding_types')
    op.drop_table('dj_sets')
    op.drop_table('dj_playlists')
    op.drop_index('idx_artists_name_trgm', table_name='artists', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('artists')
    # ### end Alembic commands ###
