"""initial schema

Revision ID: 9a7f02f4bdbc
Revises:
Create Date: 2026-02-16 16:26:34.858547
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a7f02f4bdbc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_sort", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("artist_id"),
    )
    op.create_table(
        "dj_playlists",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("parent_playlist_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("source_app", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_playlist_id"], ["dj_playlists.playlist_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("playlist_id"),
    )
    op.create_table(
        "dj_sets",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("target_duration_ms", sa.Integer(), nullable=True),
        sa.Column("target_bpm_min", sa.Float(), nullable=True),
        sa.Column("target_bpm_max", sa.Float(), nullable=True),
        sa.Column("target_energy_arc", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("set_id"),
    )
    op.create_table(
        "embedding_types",
        sa.Column("embedding_type", sa.String(length=100), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("embedding_type"),
    )
    op.create_table(
        "feature_extraction_runs",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=200), nullable=False),
        sa.Column("pipeline_version", sa.String(length=50), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("code_ref", sa.String(length=200), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "genres",
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_genre_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_genre_id"], ["genres.genre_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("genre_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "keys",
        sa.Column("key_code", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("pitch_class", sa.SmallInteger(), nullable=False),
        sa.Column("mode", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("camelot", sa.String(length=5), nullable=True),
        sa.CheckConstraint("key_code = pitch_class * 2 + mode", name="ck_keys_code_deterministic"),
        sa.PrimaryKeyConstraint("key_code"),
    )
    op.create_table(
        "labels",
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_sort", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("label_id"),
    )
    op.create_table(
        "providers",
        sa.Column("provider_id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("provider_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("provider_id"),
        sa.UniqueConstraint("provider_code"),
    )
    op.create_table(
        "spotify_album_metadata",
        sa.Column("spotify_album_id", sa.String(length=100), nullable=False),
        sa.Column("album_type", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("total_tracks", sa.Integer(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("spotify_album_id"),
    )
    op.create_table(
        "spotify_artist_metadata",
        sa.Column("spotify_artist_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("spotify_artist_id"),
    )
    op.create_table(
        "spotify_playlist_metadata",
        sa.Column("spotify_playlist_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("snapshot_id", sa.String(length=100), nullable=True),
        sa.Column("owner", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("spotify_playlist_id"),
    )
    op.create_table(
        "tracks",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("title_sort", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("track_id"),
    )
    op.create_table(
        "transition_runs",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=200), nullable=False),
        sa.Column("pipeline_version", sa.String(length=50), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=True),
        sa.Column("constraints", sa.JSON(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "audio_assets",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("asset_type", sa.SmallInteger(), nullable=False),
        sa.Column("storage_uri", sa.String(length=500), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["feature_extraction_runs.run_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id"),
        sa.UniqueConstraint(
            "track_id", "asset_type", "source_run_id", name="uq_audio_assets_track_type_run"
        ),
    )
    op.create_table(
        "beatport_metadata",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("beatport_track_id", sa.String(length=100), nullable=False),
        sa.Column("beatport_release_id", sa.String(length=100), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("key_code", sa.SmallInteger(), nullable=True),
        sa.Column("length_ms", sa.Integer(), nullable=True),
        sa.Column("label_name", sa.String(length=300), nullable=True),
        sa.Column("genre_name", sa.String(length=200), nullable=True),
        sa.Column("subgenre_name", sa.String(length=200), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("preview_url", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("beatport_track_id"),
    )
    op.create_table(
        "dj_app_exports",
        sa.Column("export_id", sa.Integer(), nullable=False),
        sa.Column("target_app", sa.SmallInteger(), nullable=False),
        sa.Column("export_format", sa.String(length=50), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=True),
        sa.Column("storage_uri", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["dj_playlists.playlist_id"],
        ),
        sa.PrimaryKeyConstraint("export_id"),
    )
    op.create_table(
        "dj_beatgrid",
        sa.Column("beatgrid_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("source_app", sa.SmallInteger(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=False),
        sa.Column("first_downbeat_ms", sa.Integer(), nullable=False),
        sa.Column("grid_offset_ms", sa.Integer(), nullable=True),
        sa.Column("grid_confidence", sa.Float(), nullable=True),
        sa.Column("is_variable_tempo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_canonical", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("beatgrid_id"),
        sa.UniqueConstraint("track_id", "source_app", name="uq_beatgrid_track_source"),
    )
    op.create_table(
        "dj_cue_points",
        sa.Column("cue_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.Integer(), nullable=False),
        sa.Column("cue_kind", sa.SmallInteger(), nullable=False),
        sa.Column("hotcue_index", sa.SmallInteger(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("color_rgb", sa.Integer(), nullable=True),
        sa.Column("is_quantized", sa.Boolean(), nullable=True),
        sa.Column("source_app", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cue_id"),
    )
    op.create_table(
        "dj_library_items",
        sa.Column("library_item_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("file_uri", sa.String(length=1000), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("file_hash", sa.LargeBinary(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=50), nullable=True),
        sa.Column("bitrate_kbps", sa.Integer(), nullable=True),
        sa.Column("sample_rate_hz", sa.Integer(), nullable=True),
        sa.Column("channels", sa.SmallInteger(), nullable=True),
        sa.Column("source_app", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("library_item_id"),
    )
    op.create_table(
        "dj_playlist_items",
        sa.Column("playlist_item_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["playlist_id"], ["dj_playlists.playlist_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_item_id"),
        sa.UniqueConstraint("playlist_id", "sort_index", name="uq_playlist_items_sort"),
    )
    op.create_table(
        "dj_saved_loops",
        sa.Column("loop_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("in_ms", sa.Integer(), nullable=False),
        sa.Column("out_ms", sa.Integer(), nullable=False),
        sa.Column("length_ms", sa.Integer(), nullable=False),
        sa.Column("hotcue_index", sa.SmallInteger(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("is_active_on_load", sa.Boolean(), nullable=True),
        sa.Column("color_rgb", sa.Integer(), nullable=True),
        sa.Column("source_app", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("out_ms > in_ms AND length_ms = out_ms - in_ms", name="ck_loop_range"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("loop_id"),
    )
    op.create_table(
        "dj_set_versions",
        sa.Column("set_version_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("version_label", sa.String(length=100), nullable=True),
        sa.Column("generator_run", sa.JSON(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["set_id"], ["dj_sets.set_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("set_version_id"),
    )
    op.create_table(
        "key_edges",
        sa.Column("from_key_code", sa.SmallInteger(), nullable=False),
        sa.Column("to_key_code", sa.SmallInteger(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_key_code"],
            ["keys.key_code"],
        ),
        sa.ForeignKeyConstraint(
            ["to_key_code"],
            ["keys.key_code"],
        ),
        sa.PrimaryKeyConstraint("from_key_code", "to_key_code"),
    )
    op.create_table(
        "provider_track_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.SmallInteger(), nullable=False),
        sa.Column("provider_track_id", sa.String(length=200), nullable=False),
        sa.Column("provider_country", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_provider_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.SmallInteger(), nullable=False),
        sa.Column("provider_track_id", sa.String(length=200), nullable=False),
        sa.Column("endpoint", sa.String(length=100), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "releases",
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_date_precision", sa.String(length=5), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["label_id"], ["labels.label_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("release_id"),
    )
    op.create_table(
        "soundcloud_metadata",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("soundcloud_track_id", sa.String(length=100), nullable=False),
        sa.Column("soundcloud_user_id", sa.String(length=100), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("key_signature", sa.String(length=20), nullable=True),
        sa.Column("genre", sa.String(length=200), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("playback_count", sa.Integer(), nullable=True),
        sa.Column("favoritings_count", sa.Integer(), nullable=True),
        sa.Column("reposts_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("downloadable", sa.Boolean(), nullable=True),
        sa.Column("streamable", sa.Boolean(), nullable=True),
        sa.Column("permalink_url", sa.String(length=500), nullable=True),
        sa.Column("artwork_url", sa.String(length=500), nullable=True),
        sa.Column("label_name", sa.String(length=300), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("is_explicit", sa.Boolean(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("soundcloud_track_id"),
    )
    op.create_table(
        "spotify_audio_features",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("danceability", sa.Float(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("loudness", sa.Float(), nullable=False),
        sa.Column("speechiness", sa.Float(), nullable=False),
        sa.Column("acousticness", sa.Float(), nullable=False),
        sa.Column("instrumentalness", sa.Float(), nullable=False),
        sa.Column("liveness", sa.Float(), nullable=False),
        sa.Column("valence", sa.Float(), nullable=False),
        sa.Column("tempo", sa.Float(), nullable=False),
        sa.Column("time_signature", sa.SmallInteger(), nullable=False),
        sa.Column("key", sa.SmallInteger(), nullable=False),
        sa.Column("mode", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
    )
    op.create_table(
        "spotify_metadata",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=False),
        sa.Column("spotify_album_id", sa.String(length=100), nullable=True),
        sa.Column("explicit", sa.Boolean(), nullable=False),
        sa.Column("popularity", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("preview_url", sa.String(length=500), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_date_precision", sa.String(length=5), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["spotify_album_id"], ["spotify_album_metadata.spotify_album_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("spotify_track_id"),
    )
    op.create_table(
        "track_artists",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role BETWEEN 0 AND 2", name="ck_track_artists_role"),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.artist_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "artist_id", "role"),
    )
    op.create_table(
        "track_audio_features_computed",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=False),
        sa.Column("tempo_confidence", sa.Float(), nullable=False),
        sa.Column("bpm_stability", sa.Float(), nullable=False),
        sa.Column("is_variable_tempo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("lufs_i", sa.Float(), nullable=False),
        sa.Column("lufs_s_mean", sa.Float(), nullable=True),
        sa.Column("lufs_m_max", sa.Float(), nullable=True),
        sa.Column("rms_dbfs", sa.Float(), nullable=False),
        sa.Column("true_peak_db", sa.Float(), nullable=True),
        sa.Column("crest_factor_db", sa.Float(), nullable=True),
        sa.Column("lra_lu", sa.Float(), nullable=True),
        sa.Column("energy_mean", sa.Float(), nullable=False),
        sa.Column("energy_max", sa.Float(), nullable=False),
        sa.Column("energy_std", sa.Float(), nullable=False),
        sa.Column("energy_slope_mean", sa.Float(), nullable=True),
        sa.Column("sub_energy", sa.Float(), nullable=True),
        sa.Column("low_energy", sa.Float(), nullable=True),
        sa.Column("lowmid_energy", sa.Float(), nullable=True),
        sa.Column("mid_energy", sa.Float(), nullable=True),
        sa.Column("highmid_energy", sa.Float(), nullable=True),
        sa.Column("high_energy", sa.Float(), nullable=True),
        sa.Column("low_high_ratio", sa.Float(), nullable=True),
        sa.Column("sub_lowmid_ratio", sa.Float(), nullable=True),
        sa.Column("centroid_mean_hz", sa.Float(), nullable=True),
        sa.Column("rolloff_85_hz", sa.Float(), nullable=True),
        sa.Column("rolloff_95_hz", sa.Float(), nullable=True),
        sa.Column("flatness_mean", sa.Float(), nullable=True),
        sa.Column("flux_mean", sa.Float(), nullable=True),
        sa.Column("flux_std", sa.Float(), nullable=True),
        sa.Column("slope_db_per_oct", sa.Float(), nullable=True),
        sa.Column("contrast_mean_db", sa.Float(), nullable=True),
        sa.Column("key_code", sa.SmallInteger(), nullable=False),
        sa.Column("key_confidence", sa.Float(), nullable=False),
        sa.Column("is_atonal", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("chroma", sa.String(length=500), nullable=True),
        sa.Column("hnr_mean_db", sa.Float(), nullable=True),
        sa.Column("chroma_entropy", sa.Float(), nullable=True),
        sa.Column("mfcc_vector", sa.String(length=500), nullable=True),
        sa.Column("hp_ratio", sa.Float(), nullable=True),
        sa.Column("onset_rate_mean", sa.Float(), nullable=True),
        sa.Column("onset_rate_max", sa.Float(), nullable=True),
        sa.Column("pulse_clarity", sa.Float(), nullable=True),
        sa.Column("kick_prominence", sa.Float(), nullable=True),
        sa.Column(
            "computed_from_asset_type", sa.SmallInteger(), server_default="0", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["key_code"],
            ["keys.key_code"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["feature_extraction_runs.run_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "run_id"),
    )
    op.create_table(
        "track_embeddings",
        sa.Column("embedding_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("embedding_type", sa.String(length=100), nullable=False),
        sa.Column("vector", sa.String(length=10000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["embedding_type"],
            ["embedding_types.embedding_type"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["feature_extraction_runs.run_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("embedding_id"),
        sa.UniqueConstraint(
            "track_id", "embedding_type", "run_id", name="uq_embeddings_track_type_run"
        ),
    )
    op.create_table(
        "track_genres",
        sa.Column("track_genre_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("source_provider_id", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.genre_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_provider_id"], ["providers.provider_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_genre_id"),
        sa.UniqueConstraint(
            "track_id", "genre_id", "source_provider_id", name="uq_track_genres_composite"
        ),
    )
    op.create_table(
        "track_sections",
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("section_type", sa.SmallInteger(), nullable=False),
        sa.Column("section_duration_ms", sa.Integer(), nullable=False),
        sa.Column("section_energy_mean", sa.Float(), nullable=True),
        sa.Column("section_energy_max", sa.Float(), nullable=True),
        sa.Column("section_energy_slope", sa.Float(), nullable=True),
        sa.Column("section_centroid_hz", sa.Float(), nullable=True),
        sa.Column("section_flux", sa.Float(), nullable=True),
        sa.Column("section_onset_rate", sa.Float(), nullable=True),
        sa.Column("section_pulse_clarity", sa.Float(), nullable=True),
        sa.Column("boundary_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["feature_extraction_runs.run_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("section_id"),
        sa.UniqueConstraint("section_id", "track_id", name="uq_sections_track"),
    )
    op.create_table(
        "track_timeseries_refs",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("feature_set", sa.String(length=100), nullable=False),
        sa.Column("storage_uri", sa.String(length=500), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("hop_length", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("dtype", sa.String(length=20), nullable=False),
        sa.Column("shape", sa.String(length=50), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["feature_extraction_runs.run_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "run_id", "feature_set"),
    )
    op.create_table(
        "transition_candidates",
        sa.Column("from_track_id", sa.Integer(), nullable=False),
        sa.Column("to_track_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("bpm_distance", sa.Float(), nullable=False),
        sa.Column("key_distance", sa.Float(), nullable=False),
        sa.Column("embedding_similarity", sa.Float(), nullable=True),
        sa.Column("energy_delta", sa.Float(), nullable=True),
        sa.Column("is_fully_scored", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("from_track_id <> to_track_id", name="ck_candidates_direction"),
        sa.ForeignKeyConstraint(["from_track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["transition_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("from_track_id", "to_track_id", "run_id"),
    )
    op.create_table(
        "transitions",
        sa.Column("transition_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("from_track_id", sa.Integer(), nullable=False),
        sa.Column("to_track_id", sa.Integer(), nullable=False),
        sa.Column("from_section_id", sa.Integer(), nullable=True),
        sa.Column("to_section_id", sa.Integer(), nullable=True),
        sa.Column("overlap_ms", sa.Integer(), nullable=False),
        sa.Column("bpm_distance", sa.Float(), nullable=False),
        sa.Column("energy_step", sa.Float(), nullable=False),
        sa.Column("centroid_gap_hz", sa.Float(), nullable=True),
        sa.Column("low_conflict_score", sa.Float(), nullable=True),
        sa.Column("overlap_score", sa.Float(), nullable=True),
        sa.Column("groove_similarity", sa.Float(), nullable=True),
        sa.Column("key_distance_weighted", sa.Float(), nullable=True),
        sa.Column("transition_quality", sa.Float(), nullable=False),
        sa.Column("trans_feature", sa.String(length=500), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("from_track_id <> to_track_id", name="ck_transitions_direction"),
        sa.ForeignKeyConstraint(["from_track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["transition_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transition_id"),
    )
    op.create_table(
        "yandex_metadata",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("yandex_track_id", sa.String(length=50), nullable=False),
        sa.Column("yandex_album_id", sa.String(length=50), nullable=True),
        sa.Column("album_title", sa.String(length=500), nullable=True),
        sa.Column("album_type", sa.String(length=50), nullable=True),
        sa.Column("album_genre", sa.String(length=100), nullable=True),
        sa.Column("album_year", sa.Integer(), nullable=True),
        sa.Column("label_name", sa.String(length=300), nullable=True),
        sa.Column("release_date", sa.String(length=10), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cover_uri", sa.String(length=500), nullable=True),
        sa.Column("explicit", sa.Boolean(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
    )
    op.create_index(
        op.f("ix_yandex_metadata_yandex_track_id"),
        "yandex_metadata",
        ["yandex_track_id"],
        unique=True,
    )
    op.create_table(
        "dj_beatgrid_change_points",
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.Column("beatgrid_id", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.Integer(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["beatgrid_id"], ["dj_beatgrid.beatgrid_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("point_id"),
    )
    op.create_table(
        "dj_set_constraints",
        sa.Column("constraint_id", sa.Integer(), nullable=False),
        sa.Column("set_version_id", sa.Integer(), nullable=False),
        sa.Column("constraint_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["set_version_id"], ["dj_set_versions.set_version_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("constraint_id"),
    )
    op.create_table(
        "dj_set_items",
        sa.Column("set_item_id", sa.Integer(), nullable=False),
        sa.Column("set_version_id", sa.Integer(), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("transition_id", sa.Integer(), nullable=True),
        sa.Column("in_section_id", sa.Integer(), nullable=True),
        sa.Column("out_section_id", sa.Integer(), nullable=True),
        sa.Column("mix_in_ms", sa.Integer(), nullable=True),
        sa.Column("mix_out_ms", sa.Integer(), nullable=True),
        sa.Column("planned_eq", sa.JSON(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["set_version_id"], ["dj_set_versions.set_version_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transition_id"], ["transitions.transition_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("set_item_id"),
        sa.UniqueConstraint("set_version_id", "sort_index", name="uq_set_items_sort"),
    )
    op.create_table(
        "track_releases",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("track_number", sa.SmallInteger(), nullable=True),
        sa.Column("disc_number", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["release_id"], ["releases.release_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "release_id"),
    )
    op.create_table(
        "dj_set_feedback",
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column("set_version_id", sa.Integer(), nullable=False),
        sa.Column("set_item_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("feedback_type", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["set_item_id"], ["dj_set_items.set_item_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["set_version_id"], ["dj_set_versions.set_version_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dj_set_feedback")
    op.drop_table("track_releases")
    op.drop_table("dj_set_items")
    op.drop_table("dj_set_constraints")
    op.drop_table("dj_beatgrid_change_points")
    op.drop_index(op.f("ix_yandex_metadata_yandex_track_id"), table_name="yandex_metadata")
    op.drop_table("yandex_metadata")
    op.drop_table("transitions")
    op.drop_table("transition_candidates")
    op.drop_table("track_timeseries_refs")
    op.drop_table("track_sections")
    op.drop_table("track_genres")
    op.drop_table("track_embeddings")
    op.drop_table("track_audio_features_computed")
    op.drop_table("track_artists")
    op.drop_table("spotify_metadata")
    op.drop_table("spotify_audio_features")
    op.drop_table("soundcloud_metadata")
    op.drop_table("releases")
    op.drop_table("raw_provider_responses")
    op.drop_table("provider_track_ids")
    op.drop_table("key_edges")
    op.drop_table("dj_set_versions")
    op.drop_table("dj_saved_loops")
    op.drop_table("dj_playlist_items")
    op.drop_table("dj_library_items")
    op.drop_table("dj_cue_points")
    op.drop_table("dj_beatgrid")
    op.drop_table("dj_app_exports")
    op.drop_table("beatport_metadata")
    op.drop_table("audio_assets")
    op.drop_table("transition_runs")
    op.drop_table("tracks")
    op.drop_table("spotify_playlist_metadata")
    op.drop_table("spotify_artist_metadata")
    op.drop_table("spotify_album_metadata")
    op.drop_table("providers")
    op.drop_table("labels")
    op.drop_table("keys")
    op.drop_table("genres")
    op.drop_table("feature_extraction_runs")
    op.drop_table("embedding_types")
    op.drop_table("dj_sets")
    op.drop_table("dj_playlists")
    op.drop_table("artists")
    # ### end Alembic commands ###
