"""ORM model package."""

from __future__ import annotations

from app.models.base import Base
from app.models.catalog import (
    Artist,
    Genre,
    Label,
    Provider,
    Release,
    Track,
    TrackArtist,
    TrackGenre,
    TrackRelease,
)
from app.models.dj import (
    DjAppExport,
    DjBeatgrid,
    DjBeatgridChangePoint,
    DjCuePoint,
    DjLibraryItem,
    DjPlaylist,
    DjPlaylistItem,
    DjSavedLoop,
)
from app.models.features import (
    AudioAsset,
    EmbeddingType,
    FeatureExtractionRun,
    Key,
    KeyEdge,
    TrackAudioFeatureComputed,
    TrackEmbedding,
    TrackSection,
    TrackTimeseriesRef,
    Transition,
    TransitionCandidate,
    TransitionRun,
)
from app.models.providers import (
    BeatportMetadata,
    ProviderTrackId,
    RawProviderResponse,
    SoundcloudMetadata,
    SpotifyAlbumMetadata,
    SpotifyArtistMetadata,
    SpotifyAudioFeature,
    SpotifyMetadata,
    SpotifyPlaylistMetadata,
)
from app.models.sets import (
    DjSet,
    DjSetConstraint,
    DjSetFeedback,
    DjSetItem,
    DjSetVersion,
)

__all__ = [
    "Artist",
    "AudioAsset",
    "Base",
    "BeatportMetadata",
    "DjAppExport",
    "DjBeatgrid",
    "DjBeatgridChangePoint",
    "DjCuePoint",
    "DjLibraryItem",
    "DjPlaylist",
    "DjPlaylistItem",
    "DjSavedLoop",
    "DjSet",
    "DjSetConstraint",
    "DjSetFeedback",
    "DjSetItem",
    "DjSetVersion",
    "EmbeddingType",
    "FeatureExtractionRun",
    "Genre",
    "Key",
    "KeyEdge",
    "Label",
    "Provider",
    "ProviderTrackId",
    "RawProviderResponse",
    "Release",
    "SoundcloudMetadata",
    "SpotifyAlbumMetadata",
    "SpotifyArtistMetadata",
    "SpotifyAudioFeature",
    "SpotifyMetadata",
    "SpotifyPlaylistMetadata",
    "Track",
    "TrackArtist",
    "TrackAudioFeatureComputed",
    "TrackEmbedding",
    "TrackGenre",
    "TrackRelease",
    "TrackSection",
    "TrackTimeseriesRef",
    "Transition",
    "TransitionCandidate",
    "TransitionRun",
]
